# Generated by Django 4.2.2 on 2023-06-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('site_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('site_phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('site_time', models.CharField(max_length=200, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
