# Generated by Django 4.2.2 on 2023-06-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_delete_sitetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_day',
            field=models.DateField(verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='site_name',
            field=models.TextField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='site_phone',
            field=models.TextField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='site_time',
            field=models.TextField(max_length=50, verbose_name='Время'),
        ),
    ]
